"""add monthly_months_since_flip to scanner_results

Revision ID: 2c467f9dc8ee
Revises: 004
Create Date: 2026-05-31 19:36:10.045886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c467f9dc8ee'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scanner_results', sa.Column('monthly_months_since_flip', sa.Integer(), nullable=True))
    op.drop_index('idx_scanner_monthly_candle', table_name='scanner_results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_scanner_monthly_candle', 'scanner_results', ['scan_date', 'monthly_candle_color'], unique=False)
    op.drop_column('scanner_results', 'monthly_months_since_flip')
    # ### end Alembic commands ###
